###############################################################################
# modules/identity/break_glass.tf
#
# The single break-glass IAM user. Per R6: "All human access goes
# through IAM Identity Center with MFA enforced; no IAM users
# except one break-glass."
#
# Why a break-glass user at all: if IdC is the SOLE human access
# path and IdC goes down (rare but possible: account-level outage
# in the IdC control plane, or a misconfigured permission set
# that locks out the admin group), the team needs a path back in.
# This user is the documented escape hatch.
#
# Posture:
#   - Username: niahealth-<env>-break-glass
#   - Login profile password: generated, stored in Secrets Manager
#     (NOT in plain text on disk; the orchestrator retrieves it
#     when printing the envelope)
#   - Virtual MFA device: the seed is generated and stored in
#     Secrets Manager (same reason)
#   - Inline policy: AdministratorAccess (intentionally wide -- the
#     point of the break-glass role is full access). The MFA +
#     EventBridge paging compensate for the breadth.
#   - Explicit Deny: iam:CreateAccessKey, iam:UpdateAssumeRolePolicy,
#     kms:ScheduleKeyDeletion -- the "don't burn the bridge on the
#     way out" rules. A break-glass session cannot create new long-
#     lived credentials or weaken the trust policies it relies on.
#   - Explicit MFA-gated Deny: s3:DeleteObject on the audit +
#     state buckets UNLESS the caller is MFA-authenticated. This
#     prevents an accidental console-only session from destroying
#     audit evidence or Terraform state.
#   - EventBridge rule: pages the SNS topic within 60s of a console
#     sign-in event for this user. The SNS topic's subscriber list
#     is owned by U9's on-call rotation.
#
# The user's login profile + MFA seed are sensitive -- they are
# stored in Secrets Manager so the orchestrator can print the
# envelope via a privileged process (not committed to git).
###############################################################################

resource "aws_iam_user" "break_glass" {
  name = "${local.name_prefix}-break-glass"
  path = "/break-glass/"

  tags = merge(var.tags, {
    Purpose = "break-glass"
    Owner   = "niahealth-security"
  })
}

# Login profile: the AWS provider auto-generates a password and
# the result is exposed via the resource's attributes
# (password, encrypted_password). We retrieve it via the
# aws_secretsmanager_secret_version resource below so the
# envelope-print script and the live login profile stay in sync.
#
# password_reset_required = false: this is a break-glass user;
# forcing a reset on first login would block the emergency use
# case. The plan documents the manual rotation procedure after
# every use.
resource "aws_iam_user_login_profile" "break_glass" {
  user                    = aws_iam_user.break_glass.name
  password_reset_required = false
}

# Secrets Manager: hold the break-glass console password. The
# orchestrator retrieves this when printing the envelope.
resource "aws_secretsmanager_secret" "break_glass_password" {
  name        = "${local.name_prefix}/break-glass-password"
  description = "Console password for the break-glass IAM user. Sensitive; do not commit. Retrieved by infra/scripts/break-glass-envelope.sh.tpl at envelope-print time."

  tags = merge(var.tags, {
    Purpose = "break-glass"
    Owner   = "niahealth-security"
  })
}

# Mirror the auto-generated login profile password into Secrets
# Manager so the envelope-print script can read it. The
# `password` attribute is a write-only value from the user's
# perspective -- Terraform can read it back via a data source,
# but the simpler pattern is `aws_secretsmanager_secret_version`
# with the value pulled from the login profile.
resource "aws_secretsmanager_secret_version" "break_glass_password_initial" {
  secret_id     = aws_secretsmanager_secret.break_glass_password.id
  secret_string = aws_iam_user_login_profile.break_glass.password

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Virtual MFA device. The seed is generated by AWS; we expose it
# via the qr_code_png + secret attributes and store the secret
# in Secrets Manager below.
resource "aws_iam_virtual_mfa_device" "break_glass" {
  virtual_mfa_device_name = "${local.name_prefix}-break-glass-mfa"
  path                    = "/break-glass/"
}

# Attach the MFA device to the user via the AWS CLI / console
# after first apply: the Terraform AWS provider does not expose
# a `aws_iam_user_mfa_device` resource, and the MFA device
# cannot be attached until the user has authenticated with it
# once (the QR-code scan is a one-time activation step). The
# activation is documented in the U9 runbook; the Terraform
# side creates the virtual MFA device and stores the seed so
# the orchestrator can print it in the envelope.

# Secrets Manager: hold the MFA device seed. Same retrieval path.
resource "aws_secretsmanager_secret" "break_glass_mfa_seed" {
  name        = "${local.name_prefix}/break-glass-mfa-seed"
  description = "MFA seed for the break-glass IAM user's virtual MFA device. Sensitive; do not commit. Retrieved by infra/scripts/break-glass-envelope.sh.tpl at envelope-print time."

  tags = merge(var.tags, {
    Purpose = "break-glass"
    Owner   = "niahealth-security"
  })
}

resource "aws_secretsmanager_secret_version" "break_glass_mfa_seed_initial" {
  secret_id     = aws_secretsmanager_secret.break_glass_mfa_seed.id
  secret_string = aws_iam_virtual_mfa_device.break_glass.base_32_string_seed

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# ============================================================================
# BREAK-GLASS INLINE POLICY
#
# Layered as: Allow AdministratorAccess + Deny the actions that
# would compound the breach if the session is itself compromised.
# ============================================================================
data "aws_iam_policy_document" "break_glass_inline" {
  # Allow: broad admin. Intentional. The whole point of the
  # break-glass path is full account access; the MFA + paging
  # compensate for the breadth.
  statement {
    sid    = "AllowAdministratorAccess"
    effect = "Allow"

    actions = ["*"]

    resources = ["*"]
  }

  # Deny: never create a long-lived access key. A break-glass
  # session is a one-off; it should NEVER generate static keys
  # that outlive the session.
  statement {
    sid    = "DenyCreateAccessKey"
    effect = "Deny"

    actions = [
      "iam:CreateAccessKey",
      "iam:UpdateAccessKey",
      "iam:DeleteAccessKey",
    ]

    resources = ["*"]
  }

  # Deny: never update assume-role policies. A compromised
  # break-glass session cannot widen the trust of an existing
  # role to grant itself persistent access.
  statement {
    sid    = "DenyUpdateAssumeRolePolicy"
    effect = "Deny"

    actions = [
      "iam:UpdateAssumeRolePolicy",
      "iam:CreateRole",
      "iam:AttachRolePolicy",
      "iam:PutRolePolicy",
    ]

    resources = ["*"]
  }

  # Deny: never schedule key deletion. PHI encryption must
  # survive a break-glass session.
  statement {
    sid    = "DenyScheduleKeyDeletion"
    effect = "Deny"

    actions = [
      "kms:ScheduleKeyDeletion",
      "kms:DisableKey",
      "kms:PutKeyPolicy",
      "kms:CreateAlias",
      "kms:DeleteAlias",
    ]

    resources = ["*"]
  }

  # Deny: never delete S3 objects in the audit or state buckets
  # unless MFA is present. The default console-only session (no
  # MFA) cannot destroy audit evidence or Terraform state.
  statement {
    sid    = "DenyDeleteAuditAndStateBucketsWithoutMfa"
    effect = "Deny"

    actions = [
      "s3:DeleteObject",
      "s3:DeleteBucket",
      "s3:DeleteObjectVersion",
    ]

    resources = [
      "${local.audit_bucket_arn}",
      "${local.audit_bucket_arn}/*",
      "arn:${data.aws_partition.current.partition}:s3:::${local.state_bucket_prefix}*",
      "arn:${data.aws_partition.current.partition}:s3:::${local.state_bucket_prefix}*/*",
    ]

    condition {
      test     = "Bool"
      variable = "aws:MultiFactorAuthPresent"
      values   = ["false"]
    }
  }
}

resource "aws_iam_user_policy" "break_glass_inline" {
  name   = "${local.name_prefix}-break-glass-inline"
  user   = aws_iam_user.break_glass.name
  policy = data.aws_iam_policy_document.break_glass_inline.json
}

# ============================================================================
# PAGING INFRASTRUCTURE
#
# EventBridge rule: fires on every aws.console-login event where
# the user is the break-glass user. Target: SNS topic. The
# `state` filter on "fail" + the absence of `MFAUsed` are NOT
# applied because the plan is "page on EVERY login, period."
# ============================================================================
resource "aws_sns_topic" "break_glass_paging" {
  name              = "${local.name_prefix}-break-glass-paging"
  display_name      = "NiaHealth Break-Glass Paging"
  kms_master_key_id = var.cwl_kms_key_arn

  tags = merge(var.tags, {
    Purpose = "break-glass-paging"
    Owner   = "niahealth-security"
  })
}

# SNS topic policy: allow EventBridge to publish to it.
data "aws_iam_policy_document" "break_glass_paging_topic_policy" {
  statement {
    sid    = "AllowEventBridgePublish"
    effect = "Allow"

    actions = [
      "SNS:Publish",
    ]

    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }

    resources = ["arn:${data.aws_partition.current.partition}:sns:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:${local.name_prefix}-break-glass-paging"]

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceAccount"
      values   = [data.aws_caller_identity.current.account_id]
    }
  }
}

resource "aws_sns_topic_policy" "break_glass_paging" {
  arn    = aws_sns_topic.break_glass_paging.arn
  policy = data.aws_iam_policy_document.break_glass_paging_topic_policy.json
}

# EventBridge rule: match console sign-in events for the
# break-glass user. The rule fires within ~60s (the EventBridge
# default delivery cadence; CloudTrail management events are
# typically delivered in under 5 minutes but AWS Console
# sign-in events go through CloudTrail as eventName
# "ConsoleLogin" with eventSource "signin.amazonaws.com").
resource "aws_cloudwatch_event_rule" "break_glass_console_login" {
  name        = "${local.name_prefix}-break-glass-console-login"
  description = "Fires on every ConsoleLogin event for the break-glass user. Target: SNS topic. Investigate every fire."
  state       = "ENABLED"

  event_pattern = jsonencode({
    "detail-type" = ["AWS Console Sign-In via CloudTrail"]
    "detail" = {
      "eventName" = ["ConsoleLogin"]
      "userIdentity" = {
        "userName" = [aws_iam_user.break_glass.name]
      }
    }
  })

  tags = merge(var.tags, {
    Purpose = "break-glass-paging"
    Owner   = "niahealth-security"
  })
}

resource "aws_cloudwatch_event_target" "break_glass_console_login" {
  rule      = aws_cloudwatch_event_rule.break_glass_console_login.name
  arn       = aws_sns_topic.break_glass_paging.arn
  target_id = "break-glass-paging-sns"
}

# CloudWatch Logs delivery for the EventBridge rule so the
# paging event is durable even if the SNS subscriber is
# misconfigured. U5 owns the long-term log archival to S3;
# this log group is the immediate retention.
resource "aws_cloudwatch_log_group" "break_glass_paging" {
  name              = "/aws/events/${local.name_prefix}-break-glass-paging"
  retention_in_days = 365
  kms_key_id        = var.cwl_kms_key_arn

  tags = merge(var.tags, {
    Purpose = "break-glass-paging"
    Owner   = "niahealth-security"
  })
}

resource "aws_iam_role" "eventbridge_log_delivery" {
  name        = "${local.name_prefix}-eventbridge-log-delivery"
  description = "Allows EventBridge to deliver break-glass sign-in events to the CloudWatch Logs log group."

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = "sts:AssumeRole"
      Principal = {
        Service = "events.amazonaws.com"
      }
      Condition = {
        StringEquals = {
          "aws:SourceAccount" = data.aws_caller_identity.current.account_id
        }
      }
    }]
  })

  tags = merge(var.tags, {
    Purpose = "break-glass-paging"
    Owner   = "niahealth-security"
  })
}

resource "aws_iam_role_policy" "eventbridge_log_delivery_inline" {
  name = "${local.name_prefix}-eventbridge-log-delivery-inline"
  role = aws_iam_role.eventbridge_log_delivery.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogStream",
        "logs:PutLogEvents",
      ]
      Resource = "${aws_cloudwatch_log_group.break_glass_paging.arn}:*"
    }]
  })
}

resource "aws_cloudwatch_event_target" "break_glass_console_login_log" {
  rule      = aws_cloudwatch_event_rule.break_glass_console_login.name
  arn       = aws_cloudwatch_log_group.break_glass_paging.arn
  target_id = "break-glass-paging-log"
  role_arn  = aws_iam_role.eventbridge_log_delivery.arn
}