###############################################################################
# backend.tf
# S3 + DynamoDB state backend using PARTIAL configuration.
#
# The bucket, key, region, DynamoDB lock table, encryption flag, and
# KMS key are all sourced from variables (or a -backend-config file
# generated by infra/scripts/bootstrap.sh). The bootstrap script is the
# one-time entry point: it creates the bucket, the CMK, the lock table,
# and writes a backend.hcl that `terraform init` consumes.
#
# Why partial configuration: it lets the SAME Terraform code work
# against the demo `-backend=false` path (used by CI plan-only) and the
# real S3 backend (used by an interview demo or a future apply) without
# editing this file. See infra/README.md for the bootstrap flow.
###############################################################################

terraform {
  backend "s3" {
    # All values come from -backend-config or `TF_VAR_*` env vars.
    # Do NOT hardcode bucket names or KMS key IDs here -- they are
    # outputs of the bootstrap step and would create a circular dep.
    key            = "envs/dev/terraform.tfstate"
    region         = "ca-central-1"
    encrypt        = true
    dynamodb_table = "niahealth-state-lock"
    # bucket         = var.state_bucket_name         # set via -backend-config
    # kms_key_id     = var.state_bucket_kms_key_arn  # set via -backend-config
  }
}
